routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['role:Administrador','auth'])->prefix('users')->name('users.')->group(function(){
    Route::get('/','UserController@index')->name('index');
    Route::get('authenticated','UserController@authenticated')->name('authenticated');
    Route::get('/create','UserController@create')->name('create');
    Route::get('/edit/{id}','UserController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','UserController@store')->name('store');
    Route::post('/update/{id}','UserController@update')->name('update')->where('id','[0-9]');
});

Route::middleware(['role:Administrador','auth'])->prefix('clients')->name('clients.')->group(function(){
    Route::get('/','ClientController@index')->name('index');
    Route::get('/create','ClientController@create')->name('create');
    Route::get('/edit/{id}','ClientController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','ClientController@store')->name('store');
    Route::post('/update/{id}','ClientController@update')->name('update')->where('id','[0-9]+');
});

Route::middleware(['role:Administrador','auth'])->prefix('verifiers')->name('verifiers.')->group(function(){
    Route::get('/','VerifierController@index')->name('index');
    Route::get('/create','VerifierController@create')->name('create');
    Route::get('/edit/{id}','VerifierController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','VerifierController@store')->name('store');
    Route::post('/update/{id}','VerifierController@update')->name('update')->where('id','[0-9]+');
});

Route::middleware(['role:Administrador','auth'])->prefix('surveys')->name('surveys.')->group(function(){
    Route::get('/','SurveyController@index')->name('index');
    Route::get('/create','SurveyController@create')->name('create');
    Route::get('/show/{id}','SurveyController@show')->name('show')->where('id','[0-9]+');

    Route::post('/store','SurveyController@store')->name('store');
});

Route::middleware(['role:Administrador','auth'])->prefix('visits')->name('visits.')->group(function(){
    Route::get('/','VisitController@index')->name('index');
    Route::get('/create','VisitController@create')->name('create');

    Route::post('/store','VisitController@store')->name('store');
    Route::post('/import/store','VisitController@import')->name('import');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use App\User;
use App\Client;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->input('search');
        $users = User::where(DB::raw("CONCAT(name,' ',email)"),'like',"%$search%")->paginate(10);
        return view('Users.index', compact('users','search'));
    }

    public function authenticated(){
        $user = array(
            'name' => Auth::user()->name,
            'avatar' => Auth::user()->avatar
        );
        return response()->json(['user' => $user],200);
    }

    public function create(){
        $clients = Client::select('id','business_name')->get();
        return view('Users.create', compact('clients'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'                  => 'required',
            'email'                 => 'required|email|unique:users',
            'role'                  => 'required|exists:roles,name',
            'client_id'             => 'required_if:role,Cliente|required_if:criterion,Client|exists:clients,id',
            'avatar'                => 'nullable|file|mimes:jpeg,bmp,png,jpg',
            'state'                 => 'required_if:criterion,State',
            'password'              => 'required|min:8',
            'password_confirmation' => 'required|same:password',
            'criterion'             => 'nullable',
        ],[
            'name.required'                  => 'El nombre es requerido',
            'email.required'                 => 'El correo electrónico es requerido',
            'email.email'                    => 'El correo electrónico ingresado no es válido',
            'email.unique'                   => 'El correo electrónico ingresado ya está en uso',
            'role.required'                  => 'Debe seleccionar un rol de la lista',
            'role.exists'                    => 'El rol seleccionado no existe',
            'client_id.exists'               => 'El cliente seleccionado no existe',
            'avatar.file'                    => 'El archivo seleccionado no es válido',
            'avatar.mimes'                   => 'El archivo selccionado no es compatible',
            'client_id.required_if'          => 'Debe seleccionar un cliente de la lista',
            'state.required_if'              => 'Debe seleccionar un estado de la lista',
            'password.required'              => 'La contraseña es requerida',
            'password.min'                   => 'La contraseña debe tener almenos 8 caracteres',
            'password_confirmation.required' => 'La validación de contraseña es requerida',
            'password_confirmation.same'     => 'La validación de contraseña no coincide'

        ]);

        $user = new User();
        $user->name      = $request->name;
        $user->email     = $request->email;
        $user->criterion = $request->criterion;
        $user->password  = bcrypt($request->password);

        if($request->role == 'Cliente'):
            $user->client_id = $request->client_id;
        endif;
        if($request->role == 'Supervisor'):
            if($request->criterion == 'Client'):
                $user->client_id = $request->client_id;
            else:
                $user->state = $request->state;
            endif;
        endif;

        if($request->file('avatar')):
            $file = $request->file('avatar');
            $filename = uniqid().".".$file->getClientOriginalExtension();
            $file_path = public_path('/images/avatars');
            $file->move($file_path,$filename);

            $user->avatar = $filename;
        endif;

        $user->save();

        $user->assignRole($request->role);

        return redirect()->route('users.index')->withStatus('Usuario registrado correctamente');
    }

    public function edit($id)
    {
        $user = User::findOrfail($id);
        $clients = Client::select('id','business_name')->get();
        $role = $user->getRoleNames();
        return view('Users.edit',compact('user','role','clients'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name'                  => 'required',
            'email'                 => ['required','email',Rule::unique('users')->ignore($id)],
            'role'                  => 'required|exists:roles,name',
            'client_id'             => 'required_if:role,Cliente|required_if:criterion,Client|exists:clients,id',
            'avatar'                => 'nullable|file|mimes:jpeg,bmp,png,jpg',
            'state'                 => 'required_if:criterion,State',
            'password'              => 'nullable|min:8',
            'password_confirmation' => 'nullable|same:password',
            'criterion'             => 'nullable',
        ],[
            'name.required'                  => 'El nombre es requerido',
            'email.required'                 => 'El correo electrónico es requerido',
            'email.email'                    => 'El correo electrónico ingresado no es válido',
            'email.unique'                   => 'El correo electrónico ingresado ya está en uso',
            'role.required'                  => 'Debe seleccionar un rol de la lista',
            'role.exists'                    => 'El rol seleccionado no existe',
            'client_id.exists'               => 'El cliente seleccionado no existe',
            'avatar.file'                    => 'El archivo seleccionado no es válido',
            'avatar.mimes'                   => 'El archivo selccionado no es compatible',
            'client_id.required_if'          => 'Debe seleccionar un cliente de la lista',
            'state.required_if'              => 'Debe seleccionar un estado de la lista',
            'password.min'                   => 'La contraseña debe tener almenos 8 caracteres',
            'password_confirmation.same'     => 'La validación de contraseña no coincide'
        ]);

        $user = User::findOrfail($id);
        $user->name      = $request->name;
        $user->email     = $request->email;
        if($request->criterion):
            $user->criterion = $request->criterion;
        else:
            $user->criterion = null;
        endif;
        if($request->password):
            $user->password = bcrypt($request->password);
        endif;

        if($request->role == 'Cliente'):
            $user->client_id = $request->client_id;
            $user->state ="";
        endif;
        if($request->role == 'Supervisor'):
            if($request->criterion == 'Client'):
                $user->client_id = $request->client_id;
                $user->state = "";
            else:
                $user->client_id = null;
                $user->state = $request->state;
            endif;
        endif;

        if($request->file('avatar')):
            if($user->avatar != null):
                \File::delete('images/avatars/'.$user->avatar);
            endif;
            $file = $request->file('avatar');
            $filename = uniqid().".".$file->getClientOriginalExtension();
            $file_path = public_path('/images/avatars');
            $file->move($file_path,$filename);

            $user->avatar = $filename;
        endif;

        $current_roles = $user->getRoleNames();

        foreach ($current_roles as $current_role) {
            $user->removeRole($current_role);
        }

        $user->update();
        $user->assignRole($request->role);

        return redirect()->route('users.index')->withStatus('Usuario actualizado correctamente');


    }
}

resources/views/Users/create.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Usuarios')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <create-user csrf="{{ csrf_token() }}" v-bind:clients="{{ json_encode($clients) }}"></create-user>

@endsection

resources/views/Users/edit.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Usuarios')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <edit-user
        csrf="{{ csrf_token() }}"
        v-bind:user="{{ json_encode($user) }}"
        v-bind:role="{{ json_encode($role) }}"
        v-bind:clients="{{ json_encode($clients) }}"
        >
    </edit-user>

@endsection

resources/views/Users/index.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Usuarios')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')

    <div class="container-fluid content">
        <div class="row">
            <div class="col-12 form-row">
                <div class="col-lg-6">
                    <form action="">
                        <div class="input-group col-lg-8">
                            <input type="text" name="search" class="form-control form-search" placeholder="Buscar" value="{{$search}}">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary btn-search" type="button" id="button-addon2">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 text-right">
                    <a href="{{route('users.create')}}" class="btn btn-new px-4">
                        {{__('REGISTAR USUARIO')}}
                    </a>
                </div>
            </div>

            @if($users->count())
                <div class="col-12 table-responsive mt-5">
                    <table class="table table-index">
                        <thead>
                            <tr class="text-center">
                                <th><strong>{{__('Nombre')}}</strong></th>
                                <th><strong>{{__('Correo')}}</strong></th>
                                <th><strong>{{__('Rol')}}</strong></th>
                                <th><strong>{{__('Estatus')}}</strong></th>
                                <th><strong>{{__('Acciones')}}</strong></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $user)
                                <tr class="text-center">
                                    <td class="align-middle text-truncate">{{$user->name}}</td>
                                    <td class="align-middle text-truncate">{{$user->email}}</td>
                                    <td class="align-middle text-truncate">
                                        @foreach ($user->getRoleNames() as $rol)
                                            {{$rol}}
                                        @endforeach
                                    </td>
                                    <td class="align-middle text-truncate">
                                        {{$user->status ? 'Activo':'Inactivo'}}
                                    </td>
                                    <td class="align-middle text-truncate">
                                        <a href="{{route('users.edit',['id' => $user->id])}}" class="btn btn-action">
                                            <i class="fas fa-pencil-alt fa-sm"></i>
                                        </a>
                                        <button class="btn btn-action">
                                            <i class="fas fa-trash-alt fa-sm"></i>
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="col-12">
                        <div class="col-md-8 col-sm-12 float-left form-inline select-count">

                        </div>
                        <div class="col-md-4 col-sm-12 float-right">
                            {{ $users->appends(['search' => $search])->links() }}
                        </div>
                    </div>
                </div>
            @else
                <div class="col-12 text-center mt-5">
                    <i class="fas fa-map-marker-alt fa-4x icon-records"></i>
                    <h6 class="text-muted text-truncate mt-2"><strong>{{__('SIN REGISTROS')}}</strong></h6>
                </div>
            @endif
        </div>
    </div>

@endsection