routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['role:Administrador','auth'])->prefix('users')->name('users.')->group(function(){
    Route::get('/','UserController@index')->name('index');
    Route::get('authenticated','UserController@authenticated')->name('authenticated');
    Route::get('/create','UserController@create')->name('create');
    Route::get('/edit/{id}','UserController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','UserController@store')->name('store');
    Route::post('/update/{id}','UserController@update')->name('update')->where('id','[0-9]');
});

Route::middleware(['role:Administrador','auth'])->prefix('clients')->name('clients.')->group(function(){
    Route::get('/','ClientController@index')->name('index');
    Route::get('/create','ClientController@create')->name('create');
    Route::get('/edit/{id}','ClientController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','ClientController@store')->name('store');
    Route::post('/update/{id}','ClientController@update')->name('update')->where('id','[0-9]+');
});

Route::middleware(['role:Administrador','auth'])->prefix('verifiers')->name('verifiers.')->group(function(){
    Route::get('/','VerifierController@index')->name('index');
    Route::get('/create','VerifierController@create')->name('create');
    Route::get('/edit/{id}','VerifierController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','VerifierController@store')->name('store');
    Route::post('/update/{id}','VerifierController@update')->name('update')->where('id','[0-9]+');
});

Route::middleware(['role:Administrador','auth'])->prefix('surveys')->name('surveys.')->group(function(){
    Route::get('/','SurveyController@index')->name('index');
    Route::get('/create','SurveyController@create')->name('create');
    Route::get('/show/{id}','SurveyController@show')->name('show')->where('id','[0-9]+');

    Route::post('/store','SurveyController@store')->name('store');
});

Route::middleware(['role:Administrador','auth'])->prefix('visits')->name('visits.')->group(function(){
    Route::get('/','VisitController@index')->name('index');
    Route::get('/create','VisitController@create')->name('create');

    Route::post('/store','VisitController@store')->name('store');
    Route::post('/import/store','VisitController@import')->name('import');
});

app/Verifier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Verifier extends Model
{
    //
}

app/Http/Controllers/VerifierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Verifier;

class VerifierController extends Controller
{

    public function index(Request $request)
    {
        $search = $request->input('search');
        $verifiers = Verifier::where(DB::raw("CONCAT(name,' ',last_name,' ',state,' ',municipality,' ',phone)"),'like',"%$search%")->paginate(15);
        return view('Verifiers.index',compact('search','verifiers'));
    }

    public function create()
    {
        return view('Verifiers.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'         => 'required',
            'last_name'    => 'required',
            'gender'       => 'required',
            'age'          => 'required|numeric',
            'civil_status' => 'required',
            'vehicle'      => 'required|boolean',
            'state'        => 'required',
            'municipality' => 'required',
            'phone'        => 'required|numeric|digits_between:10,12',
            'bank'         => 'required',
            'bank_account' => 'required|digits:24',
            'status'       => 'required'
        ],[
            'name.required'         => 'El nombre es requerido',
            'last_name.required'    => 'Los apellidos son requeridos',
            'gender.required'       => 'Seleccione el sexo del verificador',
            'age.required'          => 'La edad es requerida',
            'age.numeric'           => 'La edad ingresada no es válida',
            'civil_status.required' => 'El estado civil es requerido',
            'vehicle.required'      => 'Seleccione una opción de vehículo',
            'state.required'        => 'El estado es requerido',
            'municipality.required' => 'El Municipio es requerido',
            'phone.required'        => 'El teléfono es requerido',
            'phone.numeric'         => 'El teléfono ingresado no es válido',
            'phone.digits_between'  => 'El teléfono debe tener almenos 10 caracteres',
            'bank.required'         => 'Seleccione una opción de banco',
            'bank_account.required' => 'La cuenta bancaría es requerida',
            'bank_account.digits'   => 'La cuenta bancaría debe tener 24 caracteres',
            'status.required'       => 'Seleccione un estatus del verificador'
        ]);

        $verifier = new Verifier();
        $verifier->name         = $request->name;
        $verifier->last_name    = $request->last_name;
        $verifier->age          = $request->age;
        $verifier->gender       = $request->gender;
        $verifier->civil_status = $request->civil_status;
        $verifier->vehicle      = $request->vehicle;
        $verifier->state        = $request->state;
        $verifier->municipality = $request->municipality;
        $verifier->phone        = $request->phone;
        $verifier->bank         = $request->bank;
        $verifier->bank_account = $request->bank_account;
        $verifier->status       = $request->status;

        $verifier->save();

        return redirect()->route('verifiers.index')->withStatus('Verificador registrado correctamente');
    }


    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $verifier = Verifier::findOrfail($id);
        return view('Verifiers.edit',compact('verifier'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name'         => 'required',
            'last_name'    => 'required',
            'gender'       => 'required',
            'age'          => 'required|numeric',
            'civil_status' => 'required',
            'vehicle'      => 'required|boolean',
            'state'        => 'required',
            'municipality' => 'required',
            'phone'        => 'required|numeric|digits_between:10,12',
            'bank'         => 'required',
            'bank_account' => 'required|digits:24',
            'status'       => 'required'
        ],[
            'name.required'         => 'El nombre es requerido',
            'last_name.required'    => 'Los apellidos son requeridos',
            'gender.required'       => 'Seleccione el sexo del verificador',
            'age.required'          => 'La edad es requerida',
            'age.numeric'           => 'La edad ingresada no es válida',
            'civil_status.required' => 'El estado civil es requerido',
            'vehicle.required'      => 'Seleccione una opción de vehículo',
            'state.required'        => 'El estado es requerido',
            'municipality.required' => 'El Municipio es requerido',
            'phone.required'        => 'El teléfono es requerido',
            'phone.numeric'         => 'El teléfono ingresado no es válido',
            'phone.digits_between'  => 'El teléfono debe tener almenos 10 caracteres',
            'bank.required'         => 'Seleccione una opción de banco',
            'bank_account.required' => 'La cuenta bancaría es requerida',
            'bank_account.digits'   => 'La cuenta bancaría debe tener 24 caracteres',
            'status.required'       => 'Seleccione un estatus del verificador'
        ]);

        $verifier = Verifier::findOrfail($id);
        $verifier->name         = $request->name;
        $verifier->last_name    = $request->last_name;
        $verifier->age          = $request->age;
        $verifier->gender       = $request->gender;
        $verifier->civil_status = $request->civil_status;
        $verifier->vehicle      = $request->vehicle;
        $verifier->state        = $request->state;
        $verifier->municipality = $request->municipality;
        $verifier->phone        = $request->phone;
        $verifier->bank         = $request->bank;
        $verifier->bank_account = $request->bank_account;
        $verifier->status       = $request->status;
        $verifier->update();

        return redirect()->route('verifiers.index')->withStatus('Verificador actualizado correctamente');
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/Verifiers/create.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Verificadores')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <create-verifier csrf="{{ csrf_token() }}"></create-verifier>

@endsection

resources/views/Verifiers/edit.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Verificadores')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <edit-verifier csrf="{{ csrf_token() }}" v-bind:verifier="{{ json_encode($verifier) }}"></edit-verifier>

@endsection

resources/views/Verifiers/index.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Verificadores')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')

    <div class="container-fluid content">
        <div class="row">
            <div class="col-12 form-row">
                <div class="col-lg-6">
                    <form action="">
                        <div class="input-group col-lg-8">
                            <input type="text" name="search" class="form-control form-search" placeholder="Buscar" value="{{$search}}">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary btn-search" type="button" id="button-addon2">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 text-right">
                    <a href="{{route('verifiers.create')}}" class="btn btn-new px-4">
                        {{__('REGISTAR VERIFICADOR')}}
                    </a>
                </div>
            </div>

            @if($verifiers->count())
                <div class="col-12 table-responsive mt-5">
                    <table class="table table-index">
                        <thead>
                            <tr class="text-center">
                                <th><strong>{{__('Nombre')}}</strong></th>
                                <th><strong>{{__('Estado')}}</strong></th>
                                <th><strong>{{__('Municipio')}}</strong></th>
                                <th><strong>{{__('Teléfono')}}</strong></th>
                                <th><strong>{{__('Acciones')}}</strong></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($verifiers as $verifier)
                                <tr class="text-center">
                                    <td class="align-middle text-truncate">{{$verifier->name." ".$verifier->last_name}}</td>
                                    <td class="align-middle text-truncate">{{$verifier->state}}</td>
                                    <td class="align-middle text-truncate">{{$verifier->municipality}}</td>
                                    <td class="align-middle text-truncate">{{$verifier->phone}}</td>
                                    <td class="align-middle text-truncate">
                                        <a href="#" class="btn btn-action">
                                            <i class="fas fa-eye fa-sm"></i>
                                        </a>
                                        <a href="{{route('verifiers.edit',['id' => $verifier->id])}}" class="btn btn-action">
                                            <i class="fas fa-pencil-alt fa-sm"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="col-12">
                        <div class="col-md-8 col-sm-12 float-left form-inline select-count">

                        </div>
                        <div class="col-md-4 col-sm-12 float-right">
                            {{ $verifiers->appends(['search' => $search])->links() }}
                        </div>
                    </div>
                </div>
            @else
                <div class="col-12 text-center mt-5">
                    <i class="fas fa-map-marker-alt fa-4x icon-records"></i>
                    <h6 class="text-muted text-truncate mt-2"><strong>{{__('SIN REGISTROS')}}</strong></h6>
                </div>
            @endif
        </div>
    </div>

@endsection