routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['role:Administrador','auth'])->prefix('users')->name('users.')->group(function(){
    Route::get('/','UserController@index')->name('index');
    Route::get('authenticated','UserController@authenticated')->name('authenticated');
    Route::get('/create','UserController@create')->name('create');
    Route::get('/edit/{id}','UserController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','UserController@store')->name('store');
    Route::post('/update/{id}','UserController@update')->name('update')->where('id','[0-9]');
});

Route::middleware(['role:Administrador','auth'])->prefix('clients')->name('clients.')->group(function(){
    Route::get('/','ClientController@index')->name('index');
    Route::get('/create','ClientController@create')->name('create');
    Route::get('/edit/{id}','ClientController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','ClientController@store')->name('store');
    Route::post('/update/{id}','ClientController@update')->name('update')->where('id','[0-9]+');
});

Route::middleware(['role:Administrador','auth'])->prefix('verifiers')->name('verifiers.')->group(function(){
    Route::get('/','VerifierController@index')->name('index');
    Route::get('/create','VerifierController@create')->name('create');
    Route::get('/edit/{id}','VerifierController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','VerifierController@store')->name('store');
    Route::post('/update/{id}','VerifierController@update')->name('update')->where('id','[0-9]+');
});

Route::middleware(['role:Administrador','auth'])->prefix('surveys')->name('surveys.')->group(function(){
    Route::get('/','SurveyController@index')->name('index');
    Route::get('/create','SurveyController@create')->name('create');
    Route::get('/show/{id}','SurveyController@show')->name('show')->where('id','[0-9]+');

    Route::post('/store','SurveyController@store')->name('store');
});

Route::middleware(['role:Administrador','auth'])->prefix('visits')->name('visits.')->group(function(){
    Route::get('/','VisitController@index')->name('index');
    Route::get('/create','VisitController@create')->name('create');

    Route::post('/store','VisitController@store')->name('store');
    Route::post('/import/store','VisitController@import')->name('import');
});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    //
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use App\Client;

class ClientController extends Controller
{

    public function index(Request $request)
    {
        $search = $request->input('search');
        $clients = Client::where(DB::raw("CONCAT(business_name,' ',street,' ',state)"),'like',"%$search%")->paginate(15);
        return view('Clients.index',compact('search','clients'));
    }

    public function create()
    {
        return view('Clients.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'business_name' => 'required|unique:clients,business_name',
            'state'         => 'required',
            'municipality'  => 'required',
            'street'        => 'required|regex:/^[a-zA-Z]([a-zA-Z-]+\s)+\d{1,4}$/',
            'neighborhood'  => 'required',
            'zipcode'       => 'nullable|numeric|digits:5',
            'phone'         => 'nullable|numeric|digits:10',
            'rfc'           => 'nullable|unique:clients,rfc|min:12|max:13'
        ],[
            'business_name.required' => 'El nombre o razón social es requerido',
            'business_name.unique'   => 'El nombre o razón social ya está en uso',
            'state.required'         => 'El estado es requerido',
            'municipality.required'  => 'El municipio es requerido',
            'street.required'        => 'La calle y número son requeridos',
            'street.regex'           => 'El formato de calle y número es incorrecto',
            'neighborhood.required'  => 'La colonia es requerida',
            'zipcode.numeric'        => 'El código postal debe ser númerico',
            'zipcode.digits'         => 'El código postal debe contener 5 caracteres',
            'phone.numeric'          => 'El teléfono debe ser númerico',
            'phone.digits'           => 'El teléfono debe contener 10 caracteres',
            'rfc.unique'             => 'El RFC ingresado ya está en uso',
            'rfc.min'                => 'El RFC debe contener 12 caracteres como mínimo',
            'rfc.max'                => 'El RFC debe contener 13 caracteres como máximo'
        ]);

        $client = new Client();
        $client->business_name = $request->business_name;
        $client->responsable   = $request->responsable;
        $client->state         = $request->state;
        $client->municipality  = $request->municipality;
        $client->street        = $request->street;
        $client->neighborhood  = $request->neighborhood;
        $client->zipcode       = $request->zipcode;
        $client->phone         = $request->phone;
        $client->rfc           = $request->rfc;

        $client->save();

        return redirect()->route('clients.index')->withStatus('Cliente registrado correctamente');
    }


    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $client = Client::findOrfail($id);

        return view('Clients.edit', compact('client'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'business_name' => ['required',Rule::unique('clients')->ignore($id)],
            'state'         => 'required',
            'municipality'  => 'required',
            'street'        => 'required|regex:/^[a-zA-Z]([a-zA-Z-]+\s)+\d{1,4}$/',
            'neighborhood'  => 'required',
            'zipcode'       => 'nullable|numeric|digits:5',
            'phone'         => 'nullable|numeric|digits:10',
            'rfc'           => ['nullable',Rule::unique('clients')->ignore($id)]
        ],[
            'business_name.required' => 'El nombre o razón social es requerido',
            'business_name.unique'   => 'El nombre o razón social ya está en uso',
            'state.required'         => 'El estado es requerido',
            'municipality.required'  => 'El municipio es requerido',
            'street.required'        => 'La calle y número son requeridos',
            'street.regex'           => 'El formato de calle y número es incorrecto',
            'neighborhood.required'  => 'La colonia es requerida',
            'zipcode.numeric'        => 'El código postal debe ser númerico',
            'zipcode.digits'         => 'El código postal debe contener 5 caracteres',
            'phone.numeric'          => 'El teléfono debe ser númerico',
            'phone.digits'           => 'El teléfono debe contener 10 caracteres',
            'rfc.unique'             => 'El RFC ingresado ya está en uso',
            'rfc.min'                => 'El RFC debe contener 12 caracteres como mínimo',
            'rfc.max'                => 'El RFC debe contener 13 caracteres como máximo'
        ]);

        $client = Client::findOrfail($id);
        $client->business_name = $request->business_name;
        $client->responsable   = $request->responsable;
        $client->state         = $request->state;
        $client->municipality  = $request->municipality;
        $client->street        = $request->street;
        $client->neighborhood  = $request->neighborhood;
        $client->zipcode       = $request->zipcode;
        $client->phone         = $request->phone;
        $client->rfc           = $request->rfc;

        $client->update();

        return redirect()->route('clients.index')->withStatus('Cliente actualizado correctamente');
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/Clients/create.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Clientes')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <create-client csrf="{{ csrf_token() }}"></create-client>

@endsection

resources/views/Clients/edit.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Clientes')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <edit-client v-bind:client="{{ json_encode($client) }}" csrf="{{ csrf_token() }}"></edit-client>

@endsection

resources/views/Clients/index.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Clientes')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')

    <div class="container-fluid content">
        <div class="row">
            <div class="col-12 form-row">
                <div class="col-lg-6">
                    <form action="">
                        <div class="input-group col-lg-8">
                            <input type="text" name="search" class="form-control form-search" placeholder="Buscar" value="{{$search}}">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary btn-search" type="button" id="button-addon2">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 text-right">
                    <a href="{{route('clients.create')}}" class="btn btn-new px-4">
                        {{__('REGISTAR CLIENTE')}}
                    </a>
                </div>
            </div>

            @if($clients->count())
                <div class="col-12 table-responsive mt-5">
                    <table class="table table-index">
                        <thead>
                            <tr class="text-center">
                                <th class="text-truncate">{{__('Nombre / Razón Social')}}</th>
                                <th class="text-truncate">{{__('Domicilio')}}</th>
                                <th class="text-truncate">{{__('Estado')}}</th>
                                <th class="text-truncate">{{__('Acciones')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($clients as $client)
                                <tr class="text-center">
                                    <td class="align-middle text-truncate">{{$client->business_name}}</td>
                                    <td class="align-middle text-truncate">{{$client->street}}</td>
                                    <td class="align-middle text-truncate">{{$client->state}}</td>
                                    <td class="align-middle text-truncate">
                                        <a href="#" class="btn btn-action">
                                            <i class="fas fa-eye fa-sm"></i>
                                        </a>
                                        <a href="{{route('clients.edit', ['id' => $client->id])}}" class="btn btn-action">
                                            <i class="fas fa-pencil-alt fa-sm"></i>
                                        </a>
                                        <button class="btn btn-action">
                                            <i class="fas fa-trash-alt fa-sm"></i>
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="col-12">
                        <div class="col-md-8 col-sm-12 float-left form-inline select-count">

                        </div>
                        <div class="col-md-4 col-sm-12 float-right">
                            {{ $clients->appends(['search' => $search])->links() }}
                        </div>
                    </div>
                </div>
            @else
                <div class="col-12 text-center mt-5">
                    <i class="fas fa-map-marker-alt fa-4x icon-records"></i>
                    <h6 class="text-muted text-truncate mt-2"><strong>{{__('SIN REGISTROS')}}</strong></h6>
                </div>
            @endif
        </div>
    </div>

@endsection