routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['role:Administrador','auth'])->prefix('users')->name('users.')->group(function(){
    Route::get('/','UserController@index')->name('index');
    Route::get('authenticated','UserController@authenticated')->name('authenticated');
    Route::get('/create','UserController@create')->name('create');
    Route::get('/edit/{id}','UserController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','UserController@store')->name('store');
    Route::post('/update/{id}','UserController@update')->name('update')->where('id','[0-9]');
});

Route::middleware(['role:Administrador','auth'])->prefix('clients')->name('clients.')->group(function(){
    Route::get('/','ClientController@index')->name('index');
    Route::get('/create','ClientController@create')->name('create');
    Route::get('/edit/{id}','ClientController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','ClientController@store')->name('store');
    Route::post('/update/{id}','ClientController@update')->name('update')->where('id','[0-9]+');
});

Route::middleware(['role:Administrador','auth'])->prefix('verifiers')->name('verifiers.')->group(function(){
    Route::get('/','VerifierController@index')->name('index');
    Route::get('/create','VerifierController@create')->name('create');
    Route::get('/edit/{id}','VerifierController@edit')->name('edit')->where('id','[0-9]+');

    Route::post('/store','VerifierController@store')->name('store');
    Route::post('/update/{id}','VerifierController@update')->name('update')->where('id','[0-9]+');
});

Route::middleware(['role:Administrador','auth'])->prefix('surveys')->name('surveys.')->group(function(){
    Route::get('/','SurveyController@index')->name('index');
    Route::get('/create','SurveyController@create')->name('create');
    Route::get('/show/{id}','SurveyController@show')->name('show')->where('id','[0-9]+');

    Route::post('/store','SurveyController@store')->name('store');
});

Route::middleware(['role:Administrador','auth'])->prefix('visits')->name('visits.')->group(function(){
    Route::get('/','VisitController@index')->name('index');
    Route::get('/create','VisitController@create')->name('create');

    Route::post('/store','VisitController@store')->name('store');
    Route::post('/import/store','VisitController@import')->name('import');
});

app/Survey.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    //
}

app/Http/Controllers/SurveyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use App\Survey;

class SurveyController extends Controller
{
    public function index(Request $request){

        $search = $request->input('search');
        $surveys = Survey::where(DB::raw("CONCAT(name,' ',total_questions)"),'like',"%$search%")->paginate(15);

        return view('Surveys.index',compact('search','surveys'));

    }

    public function create()
    {
        return view('Surveys.create');
    }

    public function store(Request $request)
    {
        // return response()->json($request);
        $validator = Validator::make($request->all(),[
            'name'            => 'required',
            'total_questions' => 'required|numeric',
            'questions'       => 'required|array'
        ],[
            'name.required'            => 'El nombre de la encuesta es requerido',
            'total_questions.required' => 'El total de preguntas es requerido',
            'total_questions.numeric'  => 'El total de preguntas debe ser numérico',
            'questions.required'       => 'La encuesta debe contener preguntas',
            'questions.array'          => 'Las preguntas no son válidas'
        ]);

        if($validator->fails()):
            return response()->json(['errors' => $validator->errors()]);
        endif;

        $survey = new Survey();
        $survey->name            = $request->name;
        $survey->total_questions = $request->total_questions;
        $survey->questions       = json_encode($request->questions);

        $survey->save();

        return response()->json(['survey' => $survey],200);

    }

    public function show($id)
    {
        $survey = Survey::findOrfail($id);
        return view('Surveys.show', compact('survey'));
    }
}

resources/views/Surveys/create.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Encuestas')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <create-survey csrf="{{ csrf_token() }}"></create-survey>

@endsection

resources/views/Surveys/index.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Encuestas')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')

    <div class="container-fluid content">
        <div class="row">
            <div class="col-12 form-row">
                <div class="col-lg-6">
                    <form action="">
                        <div class="input-group col-lg-8">
                            <input type="text" name="search" class="form-control form-search" placeholder="Buscar" value="{{$search}}">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary btn-search" type="button" id="button-addon2">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 text-right">
                    <a href="{{route('surveys.create')}}" class="btn btn-new px-4">
                        {{__('CREAR ENCUESTA')}}
                    </a>
                </div>
            </div>

            @if($surveys->count())
                <div class="col-12 table-responsive mt-5">
                    <table class="table table-index">
                        <thead>
                            <tr class="text-center">
                                <th><strong>{{__('Nombre')}}</strong></th>
                                <th><strong>{{__('# de preguntas')}}</strong></th>
                                <th><strong>{{__('Acciones')}}</strong></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($surveys as $survey)
                                <tr class="text-center">
                                    <td class="align-middle text-truncate">{{$survey->name}}</td>
                                    <td class="align-middle text-truncate">{{$survey->total_questions}}</td>
                                    <td class="align-middle text-truncate">
                                        <a href="{{ route('surveys.show', ['id' => $survey->id]) }}" class="btn btn-action">
                                            <i class="fas fa-eye fa-sm"></i>
                                        </a>
                                        <a href="#" class="btn btn-action">
                                            <i class="fas fa-pencil-alt fa-sm"></i>
                                        </a>
                                        <button class="btn btn-action">
                                            <i class="fas fa-trash-alt fa-sm"></i>
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="col-12">
                        <div class="col-md-8 col-sm-12 float-left form-inline select-count">

                        </div>
                        <div class="col-md-4 col-sm-12 float-right">
                            {{ $surveys->appends(['search' => $search])->links() }}
                        </div>
                    </div>
                </div>
            @else
                <div class="col-12 text-center mt-5">
                    <i class="fas fa-map-marker-alt fa-4x icon-records"></i>
                    <h6 class="text-muted text-truncate mt-2"><strong>{{__('SIN REGISTROS')}}</strong></h6>
                </div>
            @endif
        </div>
    </div>

@endsection

resources/views/Surveys/show.blade.php
@extends('layouts.app')
@section('title','Indexmerca - Encuestas')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <show-survey v-bind:survey="{{ json_encode($survey) }}"></show-survey>

@endsection